import type { CognitiveGroup, CycleRole, CycleState, StudyPriority } from "@/lib/db/types";

export interface AtrfCatalogEntry {
  name: string;
  slug: string;
  aliases?: string[];
  cycleRole: CycleRole;
  cycleState: CycleState;
  weightPercent: number;
  cognitiveGroup: CognitiveGroup;
  unlockAfterSlug: string | null;
  cycleSortOrder: number;
  isInCycle: boolean;
  studyPriority: StudyPriority;
  blockMinutes: number;
}

export interface AtrfTemplateSlot {
  slug: string;
  thematicFocus: string;
  studyHint: string;
}

/** 7 matérias do bloco básico + específicas ATRF, com pesos do ciclo de 12h. */
export const ATRF_CATALOG: AtrfCatalogEntry[] = [
  {
    name: "Direito Constitucional",
    slug: "direito-constitucional",
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 17,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 1,
    isInCycle: true,
    studyPriority: "VERY_HIGH",
    blockMinutes: 50,
  },
  {
    name: "Língua Portuguesa",
    slug: "portugues",
    aliases: ["Português", "Língua Portuguesa"],
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 16,
    cognitiveGroup: "LANGUAGE",
    unlockAfterSlug: null,
    cycleSortOrder: 2,
    isInCycle: true,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Raciocínio Lógico-Matemático",
    slug: "raciocinio-logico",
    aliases: ["Raciocínio Lógico"],
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 17,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: null,
    cycleSortOrder: 3,
    isInCycle: true,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Direito Tributário",
    slug: "direito-tributario",
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 17,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 4,
    isInCycle: true,
    studyPriority: "VERY_HIGH",
    blockMinutes: 50,
  },
  {
    name: "Direito Administrativo",
    slug: "direito-administrativo",
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 16,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 5,
    isInCycle: true,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Contabilidade Geral",
    slug: "contabilidade-geral",
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 8,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: null,
    cycleSortOrder: 6,
    isInCycle: true,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Fluência em Dados",
    slug: "informatica",
    aliases: ["Informática", "Tecnologia da Informação", "Fluência em Dados"],
    cycleRole: "BASE",
    cycleState: "ACTIVE",
    weightPercent: 9,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: null,
    cycleSortOrder: 7,
    isInCycle: true,
    studyPriority: "MEDIUM",
    blockMinutes: 50,
  },
  {
    name: "Direito Previdenciário",
    slug: "direito-previdenciario",
    cycleRole: "SPECIFIC",
    cycleState: "LOCKED",
    weightPercent: 16,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 10,
    isInCycle: false,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Legislação Aduaneira",
    slug: "legislacao-aduaneira",
    cycleRole: "SPECIFIC",
    cycleState: "LOCKED",
    weightPercent: 16,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 11,
    isInCycle: false,
    studyPriority: "HIGH",
    blockMinutes: 50,
  },
  {
    name: "Legislação Tributária",
    slug: "ltf",
    aliases: ["Legislação Tributária Federal"],
    cycleRole: "SPECIFIC",
    cycleState: "LOCKED",
    weightPercent: 16,
    cognitiveGroup: "LAW",
    unlockAfterSlug: "direito-tributario",
    cycleSortOrder: 12,
    isInCycle: false,
    studyPriority: "VERY_HIGH",
    blockMinutes: 50,
  },
  {
    name: "Reforma Tributária",
    slug: "ltc",
    aliases: ["Legislação Tributária sobre o Consumo", "Reforma Tributária"],
    cycleRole: "SPECIFIC",
    cycleState: "LOCKED",
    weightPercent: 16,
    cognitiveGroup: "LAW",
    unlockAfterSlug: "direito-tributario",
    cycleSortOrder: 13,
    isInCycle: false,
    studyPriority: "VERY_HIGH",
    blockMinutes: 50,
  },
  {
    name: "Língua Inglesa",
    slug: "ingles",
    aliases: ["Inglês", "Língua Inglesa"],
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "LANGUAGE",
    unlockAfterSlug: null,
    cycleSortOrder: 20,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Administração Pública",
    slug: "administracao-publica",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 21,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Administração Geral",
    slug: "administracao-geral",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 22,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Administração de Compras e Materiais",
    slug: "administracao-compras",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "LAW",
    unlockAfterSlug: null,
    cycleSortOrder: 23,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Administração Financeira",
    slug: "administracao-financeira",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: null,
    cycleSortOrder: 24,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Estatística",
    slug: "estatistica",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: null,
    cycleSortOrder: 25,
    isInCycle: false,
    studyPriority: "LOW",
    blockMinutes: 50,
  },
  {
    name: "Direito Tributário Jurisprudencial",
    slug: "direito-tributario-jurisprudencial",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "LAW",
    unlockAfterSlug: "direito-tributario",
    cycleSortOrder: 26,
    isInCycle: false,
    studyPriority: "MEDIUM",
    blockMinutes: 50,
  },
  {
    name: "Análise das Demonstrações Contábeis",
    slug: "analise-demonstracoes",
    cycleRole: "FINAL",
    cycleState: "LOCKED",
    weightPercent: 8,
    cognitiveGroup: "EXACT",
    unlockAfterSlug: "contabilidade-geral",
    cycleSortOrder: 27,
    isInCycle: false,
    studyPriority: "MEDIUM",
    blockMinutes: 50,
  },
];

export const ATRF_BASE_SLUGS = ATRF_CATALOG.filter((e) => e.cycleRole === "BASE").map((e) => e.slug);

export const TRIBUTARIO_SLUG = "direito-tributario";

/** Matriz de 12 sessões do documento (ciclo de 12h para iniciante). */
export const ATRF_12H_TEMPLATE: AtrfTemplateSlot[] = [
  {
    slug: "direito-constitucional",
    thematicFocus: "Teoria Geral da Constituição e Art. 5º",
    studyHint: "Foco na literalidade do texto constitucional.",
  },
  {
    slug: "portugues",
    thematicFocus: "Compreensão de Textos / Tipologia Textual",
    studyHint: "Resolução de questões para entender o perfil da banca.",
  },
  {
    slug: "raciocinio-logico",
    thematicFocus: "Proposições Simples e Compostas",
    studyHint: "Entender conectivos lógicos e tabela verdade.",
  },
  {
    slug: "direito-tributario",
    thematicFocus: "Conceito de Tributo e Espécies Tributárias",
    studyHint: "Matéria de base. Essencial para entender as legislações posteriores.",
  },
  {
    slug: "direito-administrativo",
    thematicFocus: "Princípios da Administração Pública",
    studyHint: "Mapear o L.I.M.P.E e os princípios implícitos.",
  },
  {
    slug: "contabilidade-geral",
    thematicFocus: "Conceitos, Objeto e Campo de Aplicação",
    studyHint: "PDF do Estratégia. Videoaula só se travar.",
  },
  {
    slug: "informatica",
    thematicFocus: "Banco de Dados / Conceitos Iniciais",
    studyHint: "Curso Fluência em Dados no Estratégia.",
  },
  {
    slug: "direito-constitucional",
    thematicFocus: "Direitos Sociais e Nacionalidade",
    studyHint: "Resolução de questões intercaladas com a sessão 01.",
  },
  {
    slug: "portugues",
    thematicFocus: "Morfologia (Substantivos, Adjetivos, Pronomes)",
    studyHint: "Teoria focada na aplicação morfológica das bancas.",
  },
  {
    slug: "raciocinio-logico",
    thematicFocus: "Equivalências Lógicas e Negação",
    studyHint: "Prática exaustiva de fórmulas lógicas no papel.",
  },
  {
    slug: "direito-tributario",
    thematicFocus: "Limitações Constitucionais ao Poder de Tributar",
    studyHint: "Princípios tributários federais (Legalidade, Anterioridade).",
  },
  {
    slug: "direito-administrativo",
    thematicFocus: "Organização Administrativa",
    studyHint: "Administração Direta e Indireta (Autarquias, Empresas Públicas).",
  },
];

export const SPECIFIC_INSERTION_ORDER = [
  "direito-previdenciario",
  "legislacao-aduaneira",
  "ltf",
  "ltc",
] as const;
